# Generated by Django 3.2.6 on 2021-08-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
